export const NAV_DATA = [
    { id: 1, name: "Hospital Info" },
    { id: 2, name: "Hospital Controls" },
    { id: 3, name: "Lab Controls" },
    { id: 4, name: "Radio Controls" },
    { id: 5, name: "Exams Selection Control" },
    { id: 6, name: "Request Controls" },
    { id: 7, name: "Hospital Remarks" },
    { id: 8, name: "Accounting" },
    { id: 9, name: "Reports' Signatures" },
    { id: 10, name: "Web Controls" },
    { id: 11, name: "LAB Web Remarks" },
    { id: 12, name: "RAD Web Remarks" },
    { id: 13, name: "User's Password" },
    { id: 14, name: "Cash Controls" },
    { id: 15, name: "Admission Controls" },
    { id: 16, name: "SMS - Admission Controls" },
    { id: 17, name: "WorkFlow Controls" },
];

export const NAV_INDEXES = {
    0: "H_I",
    1: "H_C",
    2: "L_C",
    3: "R_C",
    4: "E_S_C",
    5: "REQ_C",
    6: "H_R",
    7: "ACC",
    8: "R_S",
    9: "W_C",
    10: "L_W_R",
    11: "R_W_R",
    12: "U_P",
    13: "C_C",
    14: "A_C",
    15: "S_A_C",
    16: "W_F_C",
}

export const ARR_OF_NAV_INDEX_STATE_KEYS = [
    ["Sys_HoCode", "Sys_Comp", "Sys_InstDate", "Sys_Vers", "Sys_HisLogo", "Sys_HoName", "Sys_Clipper", "Sys_CleaningPhaseActive", "Sys_ActDict", "Sys_MedPrefix", "Sys_MedLstNo", "Sys_CardPrefix", "Sys_CardLstNo", "Sys_DicSrc", "Sys_AcceptNames", "Sys_GenMFOutPat", "Sys_TopMargin", "Sys_LeftMargin"],
    ["Sys_HoClass", "Sys_HoClassDesc", "Sys_SameNmAlrtAct", "Sys_InclFathName", "Sys_PLAlert", "Sys_AlertOnStkFlrDepReq", "Sys_AlertOnLab", "Sys_AlertOnRad", "Sys_AlertOnGex", "Sys_AlertOnOpr", "Sys_AlertOnDoc", "Sys_AlertOnRes", "Sys_AlertOnStk", "Sys_VatApp", "Sys_HoVatNo", "Sys_VatPerc", "Sys_VatstDate", "Sys_VatCtrlDate", "Sys_MofRegNo", "Sys_RCB", "Sys_AuthModPricesLab",
        "Sys_AuthModPricesRad", "Sys_AuthModPricesGen", "Sys_AuthModPricesOpr", "Sys_AuthModPricesStk",
        "Sys_AuthModPricesRes", "Sys_AuthModPricesCons", "Sys_AuthModPricesPrvLab",
        "Sys_AuthModPricesPrvRad", "Sys_AuthModPricesPrvGen", "Sys_AuthModPricesPrvOpr",
        "Sys_AuthModPricesPrvStk", "Sys_AuthModPricesPrvRes", "Sys_AuthModPricesPrvCons", "Sys_TraumaActive", "Sys_TraumaAlert", "Sys_TraumaSound", "Sys_StopOprTrs", "Sys_ORMandAllOp", "Sys_BraLblFormat", "sys_KitLblFormat", "sys_MFLblFormat", "sys_PatLblFormat", "Sys_MedLabelFormat",
    ],
    ["Sys_LbERApp", "Sys_SendExam", "Sys_LbStTime", "Sys_LbEndTime", "Sys_LbIntervalTime", "Sys_LbSpcHdr"],
    ["Sys_RdERApp", "Sys_RdStTime", "Sys_RdEndTime", "Sys_RdBedER", "Sys_RISApp", "Sys_RdIntervalTime", "Sys_RdSpcHdr", "Sys_ReqFromRIS"],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
];